spring.application.name=intern_project
spring.profiles.active=local
server.servlet.context-path=/api/v1

jwt.signer-key=4iTldiQ6EQZaW0tHDyK6EH5KPVKMMBZUPAU*e>4_;QdS_+[-otyKHh.$oxJB?Y1gFS2(uuK)(8!_#Qo+/Y%i6I
jwt.token-validity-in-seconds=86400