import { StudentDTO } from '../models/student.model';

export const MOCK_STUDENTS: StudentDTO[] = [
  {
    id: 1,
    studentCode: 'SV001',
    fullName: 'Lê Văn An',
    className: 'CNTT15A',
    cohort: 'K15',
    avatarUrl: 'https://i.pravatar.cc/150?img=5',
    dateOfBirth: '2004-03-12',
    gender: 'Nam',
    email: 'an.le@student.edu.vn',
    registeredSubjectsCount: 3,
    enrolledSubjects: [
      { subjectId: 1, subjectName: 'Lập trình Web', teacherName: 'Trần Thị Mai', processScore: 8, componentScore: 7.5, finalScore: 7.7 },
      { subjectId: 2, subjectName: 'Cấu trúc dữ liệu', teacherName: 'Phạm Minh Tuấn', processScore: 6, componentScore: 5, finalScore: 5.4 },
      { subjectId: 3, subjectName: 'Cơ sở dữ liệu', teacherName: 'Trần Thị Mai', processScore: 4, componentScore: 3, finalScore: 3.4 },
    ],
  },
  {
    id: 2,
    studentCode: 'SV002',
    fullName: 'Phạm Thị Bích',
    className: 'CNTT15A',
    cohort: 'K15',
    avatarUrl: 'https://i.pravatar.cc/150?img=9',
    dateOfBirth: '2004-07-22',
    gender: 'Nữ',
    email: 'bich.pham@student.edu.vn',
    registeredSubjectsCount: 2,
    enrolledSubjects: [
      { subjectId: 1, subjectName: 'Lập trình Web', teacherName: 'Trần Thị Mai', processScore: 9, componentScore: 8.5, finalScore: 8.7 },
      { subjectId: 2, subjectName: 'Cấu trúc dữ liệu', teacherName: 'Phạm Minh Tuấn', processScore: 7, componentScore: 6.5, finalScore: 6.7 },
    ],
  },
  {
    id: 3,
    studentCode: 'SV003',
    fullName: 'Hoàng Văn Cường',
    className: 'CNTT15B',
    cohort: 'K15',
    avatarUrl: 'https://i.pravatar.cc/150?img=15',
    dateOfBirth: '2004-01-05',
    gender: 'Nam',
    email: 'cuong.hoang@student.edu.vn',
    registeredSubjectsCount: 3,
    enrolledSubjects: [
      { subjectId: 1, subjectName: 'Lập trình Web', teacherName: 'Trần Thị Mai', processScore: 5, componentScore: 4, finalScore: 4.4 },
      { subjectId: 3, subjectName: 'Cơ sở dữ liệu', teacherName: 'Trần Thị Mai', processScore: 8, componentScore: 7, finalScore: 7.4 },
      { subjectId: 4, subjectName: 'Mạng máy tính', teacherName: 'Ngô Thị Lan', processScore: 3, componentScore: 2, finalScore: 2.4 },
    ],
  },
  {
    id: 4,
    studentCode: 'SV004',
    fullName: 'Đỗ Thị Dung',
    className: 'CNTT15B',
    cohort: 'K15',
    avatarUrl: 'https://i.pravatar.cc/150?img=20',
    dateOfBirth: '2004-11-30',
    gender: 'Nữ',
    email: 'dung.do@student.edu.vn',
    registeredSubjectsCount: 1,
    enrolledSubjects: [
      { subjectId: 4, subjectName: 'Mạng máy tính', teacherName: 'Ngô Thị Lan', processScore: 7, componentScore: 8, finalScore: 7.6 },
    ],
  },
  {
    id: 5,
    studentCode: 'SV005',
    fullName: 'Vũ Minh Đức',
    className: 'CNTT16A',
    cohort: 'K16',
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    dateOfBirth: '2005-05-18',
    gender: 'Nam',
    email: 'duc.vu@student.edu.vn',
    registeredSubjectsCount: 2,
    enrolledSubjects: [
      { subjectId: 2, subjectName: 'Cấu trúc dữ liệu', teacherName: 'Phạm Minh Tuấn', processScore: null, componentScore: null, finalScore: null },
      { subjectId: 3, subjectName: 'Cơ sở dữ liệu', teacherName: 'Trần Thị Mai', processScore: null, componentScore: null, finalScore: null },
    ],
  },
];
